Feature/components logic
marcioflaviof/lista-rango pull request #2
Opened 2022-02-10 19:07 UTC by marcioflaviof

Adding logic to the project

2022-02-11 13:44 UTC, mateusbw commented on src/components/pages/Home.jsx
> +  const [restaurants, setRestaurants] = useState([]);
Why not use the `RestaurantContext` to store restaurants data instead of the local component state? 

In this case it won't make much difference, since we are only using `restaurants` in this component, but it will help you understand when to use local component state vs global state.

2022-02-11 13:44 UTC, mateusbw commented on src/components/pages/Restaurant.jsx
> +      <MenuSearchBar styles={{ "margin-bottom": "35px" }} />
I don't think i understand the need of passing the `styles` as props here...

2022-02-11 13:44 UTC, mateusbw commented on src/routes.jsx
> +
```suggestion
const ROUTES = {
  HOME: "/",
  RESTAURANT: "/restaurant/:id"
}
```

2022-02-11 13:44 UTC, mateusbw commented on src/routes.jsx
> +      <Route path="/restaurant/:id" element={<Restaurant />} />
```suggestion
      <Route path={ROUTES.HOME} element={<Home />} />
      <Route path={ROUTES.RESTAURANT} element={<Restaurant />} />
```

2022-02-23 12:41 UTC, erickcelio requested changes

2022-02-23 12:41 UTC, erickcelio commented on src/components/atoms/CloseButton/index.jsx
> +  const closeModal = () => {
Acho que pode deixar esse método closeModal dentro do ModalContext. e já pegar ele em vez de pegar o state e setState

2022-02-23 12:41 UTC, erickcelio commented on src/components/atoms/DishCard/index.jsx
> +  }
aqui tenta englobar dentro de um useMemo, não é muito legal ter essas lógicas fora dos métodos useMemo useEffect e tal, acaba tendo renderizações e computação desnecessária

2022-02-23 12:41 UTC, erickcelio commented on src/components/atoms/RestaurantCard/index.jsx
> +  const { setState } = useContext(RestaurantContext);
Da mesma forma acho q fica menos legível deixar como setState, já que é  referente ao RestaurantContext, poderia ser algo tipo setRestaurant, ou algo q faça mais sentido

2022-02-23 12:41 UTC, erickcelio commented on src/components/atoms/RestaurantHeader/index.jsx
> +  const { state, setState } = useContext(RestaurantContext);
Mesma coisa o state talvez poderia ser restaurantInfo ou só restaurant

2022-02-23 12:41 UTC, erickcelio commented on src/components/pages/Home.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
é meio chato não conseguir fazer await dentro do useEffect mesmo, mas acho melhor tu abstrair o fetchData para um useCallback e só chamar ele como fez na 39 mesmo, e coloca ele no array de deps

2022-02-23 12:41 UTC, erickcelio commented on src/components/pages/Restaurant.jsx
> +    fetchData();
mesma coisa

2022-02-23 12:41 UTC, erickcelio commented on src/context/ModalContext.js
> +  return <ModalContext.Provider value={{ state, setState }}>{children}</ModalContext.Provider>;
igual tinha colocado, tenta deixar um nome mais claro ou realmente funções como closeModal e openModal que já ficaria bem melhor

2022-02-23 12:41 UTC, erickcelio commented on src/context/RestaurantContext.js
> +    <RestaurantContext.Provider value={{ state, setState }}>{children}</RestaurantContext.Provider>
Questão de nomeclatura igual comentei acima

2022-02-23 12:41 UTC, erickcelio commented on src/config/http.js
> +  baseURL: "https://challange.goomer.com.br",
Diexa como ENV o baseURL só pra ficar mais organizado

2022-02-23 15:52 UTC, erickcelio requested changes

2022-02-23 15:52 UTC, erickcelio commented on src/components/atoms/DishCard/index.jsx
> +    if (sales) {
```suggestion
  const isOnSale = useMemo(() => {
    if (sales) {
```

2022-02-23 15:52 UTC, erickcelio commented on src/components/pages/Home.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
pq desabilitar o eslint aqui ?

2022-02-23 15:52 UTC, erickcelio commented on src/components/pages/Home.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
se ele estiver reclamando coloca o setRestaurant na lista de dependencias, não tem problema

2022-02-23 15:52 UTC, erickcelio commented on src/components/molecules/DishModal/index.jsx
> +  };
aqui agora pode usar o método q exportou no modalContext

2022-02-23 16:45 UTC, marcioflaviof commented on src/components/pages/Home.jsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Era realmente pelo setRestaurant

2022-02-23 19:09 UTC, erickcelio approved these changes

2022-02-23 19:40 UTC, merged